---
plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
filters:
  tag:name: ivolve
  instance-state-name: running

keyed_groups:
  - key: placement.region
    parent_group: aws_region
    prefix: aws_region
    
  - key: tags.name
    parent_group: aws_tags
    prefix: tag

hostnames:
  - dns-name
  - private-ip-address
  - instance-id

compose:
  ansible_host: dns_name
  instance_id: instance_id
  instance_type: instance_type
  availability_zone: placement.availability_zone
  vpc_id: vpc_id
  security_groups: security_groups

vars:
  ansible_user: ec2-user
  ansible_port: 22
  ansible_connection: ssh
