apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3M=      # rootpass
  MYSQL_USER: YXBwdXNlcg==              # appuser
  MYSQL_PASSWORD: YXBwcGFzc3dvcmQ=      # apppassword
  MYSQL_DATABASE: aXZvbHZl              # ivolve
