---
- name: Download kubectl binary
  get_url:
    url: https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'

- name: Verify kubectl installation
  command: /usr/local/bin/kubectl version --client
  register: kubectl_version
  changed_when: false

- name: Show kubectl version
  debug:
    msg: "{{ kubectl_version.stdout }}"

